### ISSUE TITLE
cannot load biom 2.0 example file 

### ISSUE THREAD

**Issue by rec3141** [molbiodiv/biom-conversion-server#6]
![image](https://cloud.githubusercontent.com/assets/1102883/26379439/bdec5ed6-3fc5-11e7-82af-9c3226324db0.png)

This is what I get when I try to upload the example BIOM formatted file from http://biom-format.org/documentation/format_versions/biom-2.0.html

I'm also struggling to figure out how to use the conversion server API if I have the HDF5 file already loaded in a variable as text.

**Comment by iimog** [comment]
Hi @rec3141 thanks for reporting this issue.

Please note that [HDF5](http://www.hdfgroup.org/) is a binary format. The text at the bottom of the [biom-format.org example page](http://biom-format.org/documentation/format_versions/biom-2.0.html) is not HDF5. It is a description of how the content of the HDF5 file looks (in the [HDF5 data description langauge (DDL)](https://support.hdfgroup.org/HDF5/doc/ddl.html)). Therefore a text file with this content is not a proper biom file. The same probably applies for the HDF5 content you have in your text variable. In contrast biom version 1.0 is json and therefore a text format.
For handling biom version 2 make sure to create the proper binary file or store content in a [ArrayBuffer](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) variable in JavaScript.

Let me know if you encounter more problems.

**Comment by rec3141** [comment]
I see, thanks for the clarification. I wish they'd linked to the actual example files in https://github.com/biocore/biom-format/tree/master/examples, would have saved me a lot of confusion!
